apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ahmetensar-com-tr-tls
spec:
  secretName: ahmetensar-com-tr
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ahmetensar.com.tr
  dnsNames:
    - ahmetensar.com.tr
    - www.ahmetensar.com.tr
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ahmetensar.com.tr
          - www.ahmetensar.com.tr